[package]
name = "spreadsheet-plotter"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.99", features = ["backtrace"] }
csv = "1.3.1"
env_logger = "0.11.8"
getopts = "0.2.23"
log = "0.4.27"
rand = "0.9.2"

[build-dependencies]
anyhow = { version = "1.0.99", features = ["backtrace"] }

[[bin]]
name = "sp"
path = "src/main.rs"

[features]
# default = ["bc"]
bc = []